/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_bridge_AbstractOclBridge */

#ifndef _Included_ocl_bridge_AbstractOclBridge
#define _Included_ocl_bridge_AbstractOclBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    ListDevices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_bridge_AbstractOclBridge_ListDevices
  (JNIEnv *, jobject);

/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ocl_bridge_AbstractOclBridge_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_bridge_AbstractOclBridge_Dispose
  (JNIEnv *, jobject);

/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    OclMap
 * Signature: (Ljava/lang/String;[B[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ocl_bridge_AbstractOclBridge_OclMap
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    OclFilter
 * Signature: (Ljava/lang/String;[B[I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_ocl_bridge_AbstractOclBridge_OclFilter
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

/*
 * Class:     ocl_bridge_AbstractOclBridge
 * Method:    OclReduce
 * Signature: (Ljava/lang/String;[B[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ocl_bridge_AbstractOclBridge_OclReduce
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
