/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge */

#ifndef _Included_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
#define _Included_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    ListDevices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_ListDevices
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_Dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    GetKernelProfiling
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_GetKernelProfiling
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    OclMap
 * Signature: (Ljava/lang/String;[B[II[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_OclMap
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray, jint, jbyteArray);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    OclFilter
 * Signature: (Ljava/lang/String;[B[I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_OclFilter
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray);

/*
 * Class:     org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge
 * Method:    OclReduce
 * Signature: (Ljava/lang/String;[B[II[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_apache_flink_streaming_api_ocl_bridge_AbstractOclBridge_OclReduce
  (JNIEnv *, jobject, jstring, jbyteArray, jintArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
